In [5]:
import numpy as np

In [6]:
camera1 = np.load('camera_matrix_left.npy')
camera2 = np.load('camera_matrix_right.npy')
print(camera1)

[[-1.04514824e+02  5.83464687e+02  1.43107882e+03  5.14537518e+04]
 [ 1.41473913e+03  3.15313663e+02  1.35762490e+02  3.96420679e+04]
 [ 2.78339886e-02  9.98727429e-01  4.20569972e-02  7.08113145e+01]]


In [7]:
def triangulate_point(P1, P2, x1, x2):
    # Construct matrix A
    A = np.vstack((x1[0]*P1[2] - P1[0],
                   x1[1]*P1[2] - P1[1],
                   x2[0]*P2[2] - P2[0],
                   x2[1]*P2[2] - P2[1]))
    
    # Perform Singular Value Decomposition (SVD)
    _, _, V = np.linalg.svd(A)
    
    # Extract the last column of V
    X = V[-1]
    
    # Normalize homogeneous coordinates
    X /= X[3]
    
    # Return the Cartesian coordinates
    return X[:3]



In [8]:


# Define corresponding image points x1 and x2 (2x1 vectors)
x1 = np.random.rand(2, 1)
x2 = np.random.rand(2, 1)

# Triangulate the 3D point
X = triangulate_point(camera1, camera2, x1, x2)
print("Triangulated point:", X)


Triangulated point: [-11.38508505  12.19415547 -52.51250377]
